=== MaslovaEV/sj-platform/sj-crud-rest/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Run Module Specification",
  "description": "Common specification for stream-juggler modules that can be run",
  "definitions": {
    "source": {
      "type": "object",
      "properties": {
        "cardinality": {
          "description": "The boundary of interval in that a number of inputs can change",
          "type": "array",
          "items": {
            "type": "number",
            "minimum": 0
          },
          "minItems": 2,
          "maxItems": 2
        },
        "types": {
          "description": "The enumeration of types of inputs",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "stream.t-stream",
              "stream.kafka",
              "elasticsearch-output",
              "jdbc-output"
            ]
          }
        }
      },
      "required": [
        "cardinality",
        "types"
      ]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "description": "The unique name for a module",
      "type": "string"
    },
    "description": {
      "description": "The description for a module",
      "type": "string"
    },
    "version": {
      "description": "The module version",
      "type": "string"
    },
    "author": {
      "description": "The module author",
      "type": "string"
    },
    "license": {
      "description": "The software license type for a module",
      "type": "string"
    },
    "inputs": {
      "description": "The specification for the inputs of a module",
      "$ref": "#/definitions/source"
    },
    "outputs": {
      "description": "The specification for the outputs of a module",
      "$ref": "#/definitions/source"
    },
    "module-type": {
      "description": "The type of a module",
      "type": "string",
      "enum": [
        "regular-streaming",
        "windowed-streaming",
        "output-streaming"
      ]
    },
    "engine-name": {
      "description": "The name of the computing core of a module",
      "type": "string"
    },
    "engine-version": {
      "description": "The version of the computing core of a module",
      "type": "string"
    },
    "options": {
      "description": "The json-schema for some optional parameters",
      "type": "object"
    },
    "validator-class": {
      "description": "The absolute path to class that is responsible for a validation of launch options",
      "type": "string"
    },
    "executor-class": {
      "description": "The absolute path to class that is responsible for a running of module",
      "type": "string"
    }
  },
  "required": [
    "name",
    "inputs",
    "outputs",
    "module-type",
    "options",
    "validator-class",
    "executor-class"
  ]
}

=== MaslovaEV/sj-platform/contrib/stubs/sj-stub-windowed-streaming/src/main/resources/specification.json
{
  "name": "windowed-streaming-stub",
  "description": "Stub module by BW",
  "version": "1.0",
  "author": "Ksenia Mikhaleva",
  "license": "Apache 2.0",
  "inputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.kafka",
      "stream.t-stream"
    ]
  },
  "outputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.t-stream"
    ]
  },
  "module-type": "windowed-streaming",
  "engine-name": "com.bwsw.windowed.streaming.engine",
  "engine-version": "1.0",
  "options": {
    "opt": 1
  },
  "validator-class": "com.bwsw.sj.stubs.module.windowed_streaming.Validator",
  "executor-class": "com.bwsw.sj.stubs.module.windowed_streaming.Executor"
}

=== MaslovaEV/sj-platform/sj-stub-module/src/main/resources/specification.json
{
  "name": "test_stub",
  "description": "Stub module by BW",
  "version": "0.1",
  "author": "Ksenia Mikhaleva",
  "license": "Apache 2.0",
  "inputs": {
    "cardinality": [
      1,
      1
    ],
    "types": [
      "stream.t-stream"
    ]
  },
  "outputs": {
    "cardinality": [
      1,
      1
    ],
    "types": [
      "stream.t-stream"
    ]
  },
  "module-type": "regular-streaming",
  "engine-name": "regular-streaming",
  "engine-version": "0.1",
  "options": {
    "opt": 1
  },
  "validator-class": "com.bwsw.sj.module.regular.stub.Validator",
  "executor-class": "com.bwsw.sj.module.regular.stub.Executor"
}

=== MaslovaEV/sj-platform/contrib/examples/sflow/sj-sflow-process/src/main/resources/specification.json
{
  "name": "sflow-process",
  "description": "Regular module for sflow processing by BW",
  "version": "0.1",
  "author": "Ksenia Mikhaleva",
  "license": "Apache 2.0",
  "inputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.t-stream",
      "stream.kafka"
    ]
  },
  "outputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.t-stream",
      "stream.kafka"
    ]
  },
  "module-type": "regular-streaming",
  "engine-name": "com.bwsw.regular.streaming.engine",
  "engine-version": "0.1",
  "options": {},
  "validator-class": "com.bwsw.examples.sflow.module.process.Validator",
  "executor-class": "com.bwsw.examples.sflow.module.process.Executor"
}

=== MaslovaEV/sj-platform/contrib/stubs/sj-stub-regular-streaming/src/main/resources/specification.json
{
  "name": "regular-streaming-stub",
  "description": "Stub module by BW",
  "version": "0.1",
  "author": "Ksenia Mikhaleva",
  "license": "Apache 2.0",
  "inputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.kafka",
      "stream.t-stream"
    ]
  },
  "outputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.t-stream"
    ]
  },
  "module-type": "regular-streaming",
  "engine-name": "com.bwsw.regular.streaming.engine",
  "engine-version": "0.1",
  "options": {
    "opt": 1
  },
  "validator-class": "com.bwsw.sj.stubs.module.regular_streaming.Validator",
  "executor-class": "com.bwsw.sj.stubs.module.regular_streaming.Executor"
}

=== MaslovaEV/sj-platform/contrib/examples/sj-windowed-sum/src/main/resources/specification.json
{
  "name": "windowed-sum",
  "description": "Module by BW of numbers summation",
  "version": "1.0",
  "author": "Ksenia Mikhaleva",
  "license": "Apache 2.0",
  "inputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.kafka"
    ]
  },
  "outputs": {
    "cardinality": [
      1,
      10
    ],
    "types": [
      "stream.t-stream"
    ]
  },
  "module-type": "windowed-streaming",
  "engine-name": "com.bwsw.windowed.streaming.engine",
  "engine-version": "1.0",
  "options": {
  },
  "validator-class": "com.bwsw.sj.examples.sum.Validator",
  "executor-class": "com.bwsw.sj.examples.sum.Executor"
}
